"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Check, CircleHelp, CreditCard, PackageCheck, ShieldCheck, ShoppingBag, Truck, X } from "lucide-react";
import { TopBar } from "@/components/TopBar";
import { Footer } from "@/components/Footer";
import { ServiceCard } from "@/components/ServiceCard";
import { useCart } from "@/lib/cart-store";
import type { DecorCategory, DecorService } from "@/data/types";

const conditionLabels = { like_new: "Like new", excellent: "Excellent", good: "Good", fair: "Fair" };

export function ServiceDetailView({ service, category, related }: { service: DecorService; category: DecorCategory; related: DecorService[] }) {
  const router = useRouter();
  const { addItem } = useCart();
  const availableStock = Math.max(0, (service.stockQuantity ?? 1) - (service.reservedQuantity ?? 0));
  const soldOut = availableStock === 0;
  const addToCart = () => { if (soldOut) return toast.error("This item is sold out"); addItem({ id: service.id, productId: service.id, categorySlug: service.categorySlug, categoryName: category.name, serviceSlug: service.slug, serviceName: service.name, image: service.images[0] ?? "/placeholder.svg", unitPrice: service.priceDiscounted, originalPrice: service.priceOriginal }); toast.success(`${service.name} added to cart`); };
  const buyNow = () => { addToCart(); if (!soldOut) router.push("/checkout"); };
  const warranty = service.warrantyStatus && service.warrantyStatus !== "none" ? `${service.warrantyProvider ? `${service.warrantyProvider} · ` : ""}${service.warrantyCoverage ?? "Warranty available"}` : "No warranty included";

  return <div className="min-h-dvh bg-background pb-24"><TopBar /><main className="mx-auto w-full max-w-6xl px-5 py-6 md:px-8 md:py-10">
    <div className="grid gap-8 lg:grid-cols-[minmax(0,1.08fr)_minmax(22rem,.92fr)] lg:gap-12">
      <div className="grid grid-cols-2 gap-3">{service.images.slice(0, 4).map((image, index) => <div key={image} className={`relative overflow-hidden rounded-3xl bg-muted ${index === 0 ? "col-span-2 aspect-[4/3]" : "aspect-square"}`}><Image src={image} alt={`${service.name} view ${index + 1}`} fill priority={index === 0} sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></div>)}</div>
      <section className="self-start rounded-3xl border border-border bg-card p-5 shadow-card md:p-7 lg:sticky lg:top-28"><p className="text-sm font-semibold text-muted-foreground">{category.name}{service.brand ? ` · ${service.brand}` : ""}</p><h1 className="mt-2 font-display text-3xl leading-tight text-primary md:text-5xl">{service.name}</h1><p className="mt-3 leading-6 text-muted-foreground">{service.tagline}</p><div className="mt-5 flex flex-wrap gap-2">{service.conditionGrade && <span className="rounded-full bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">{conditionLabels[service.conditionGrade]}</span>}<span className={`rounded-full px-3 py-1 text-sm font-semibold ${soldOut ? "bg-destructive/10 text-destructive" : "bg-emerald-500/10 text-emerald-700"}`}>{soldOut ? "Sold out" : `${availableStock} available`}</span></div><div className="mt-6 flex items-baseline gap-3 border-y border-border py-5"><span className="text-3xl font-black text-primary">₹{service.priceDiscounted.toLocaleString("en-IN")}</span>{service.priceOriginal > service.priceDiscounted && <span className="text-lg text-muted-foreground line-through">₹{service.priceOriginal.toLocaleString("en-IN")}</span>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={addToCart} disabled={soldOut} className="flex items-center justify-center gap-2 rounded-full border border-primary px-5 py-3.5 text-sm font-bold text-primary disabled:cursor-not-allowed disabled:opacity-50"><ShoppingBag className="h-4 w-4" />Add to cart</button><button onClick={buyNow} disabled={soldOut} className="flex items-center justify-center gap-2 rounded-full bg-gradient-brand px-5 py-3.5 text-sm font-bold text-primary-foreground shadow-glow disabled:cursor-not-allowed disabled:opacity-50"><CreditCard className="h-4 w-4" />Buy now</button></div><p className="mt-4 text-center text-xs leading-5 text-muted-foreground">Choose cash on delivery or self pickup at checkout. Secure online payments are coming soon.</p></section>
    </div>
    <section className="mt-10 grid gap-6 lg:grid-cols-3"><article className="rounded-3xl border border-border bg-card p-5 md:p-7 lg:col-span-2"><h2 className="font-display text-2xl text-primary">About this item</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-muted-foreground">{service.description}</p>{service.conditionSummary && <div className="mt-7 border-t border-border pt-6"><h3 className="flex items-center gap-2 font-bold text-primary"><Check className="h-4 w-4 text-emerald-600" />Condition notes</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{service.conditionSummary}</p></div>}{service.usageSummary && <p className="mt-4 rounded-2xl bg-muted/60 p-3 text-sm text-muted-foreground"><strong className="text-foreground">Usage:</strong> {service.usageSummary}</p>}</article><aside className="rounded-3xl border border-border bg-card p-5 md:p-7"><h2 className="flex items-center gap-2 font-bold text-primary"><ShieldCheck className="h-5 w-5 text-accent" />Warranty</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{warranty}</p>{service.warrantyExpiresAt && <p className="mt-2 text-xs text-muted-foreground">Expires {new Date(service.warrantyExpiresAt).toLocaleDateString("en-IN", { month: "short", year: "numeric" })}</p>}<div className="mt-6 border-t border-border pt-6"><h2 className="flex items-center gap-2 font-bold text-primary"><Truck className="h-5 w-5 text-accent" />Delivery & pickup</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{service.deliveryInfo ?? "Choose delivery or pickup during checkout."}</p></div></aside></section>
    {(service.included.length > 0 || service.faqs.length > 0) && <section className="mt-6 grid gap-6 md:grid-cols-2">{service.included.length > 0 && <article className="rounded-3xl border border-border bg-card p-5 md:p-7"><h2 className="flex items-center gap-2 font-bold text-primary"><PackageCheck className="h-5 w-5 text-accent" />What’s included</h2><ul className="mt-4 space-y-3 text-sm text-muted-foreground">{service.included.map((item) => <li key={item} className="flex gap-2"><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{item}</li>)}</ul>{service.notIncluded.length > 0 && <><h3 className="mt-6 border-t border-border pt-5 font-bold text-primary">Not included</h3><ul className="mt-3 space-y-3 text-sm text-muted-foreground">{service.notIncluded.map((item) => <li key={item} className="flex gap-2"><X className="mt-0.5 h-4 w-4 shrink-0 text-destructive" />{item}</li>)}</ul></>}</article>}{service.faqs.length > 0 && <article className="rounded-3xl border border-border bg-card p-5 md:p-7"><h2 className="flex items-center gap-2 font-bold text-primary"><CircleHelp className="h-5 w-5 text-accent" />FAQs</h2><div className="mt-4 divide-y divide-border">{service.faqs.map((faq) => <div key={faq.question} className="py-4 first:pt-0"><h3 className="text-sm font-bold text-primary">{faq.question}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{faq.answer}</p></div>)}</div></article>}</section>}
    {related.length > 0 && <section className="mt-12"><h2 className="font-display text-2xl text-primary">You may also like</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{related.map((item) => <ServiceCard key={item.id} service={item} compact />)}</div></section>}
  </main><Footer /></div>;
}
