import Image from "next/image";
import Link from "next/link";
import { Star } from "lucide-react";
import type { DecorService } from "@/data/types";

export function ServiceCard({ service, size = "sm", compact = false }: { service: DecorService; badge?: "trending" | "featured"; size?: "sm" | "md"; compact?: boolean }) {
  const available = Math.max(0, (service.stockQuantity ?? 1) - (service.reservedQuantity ?? 0));
  return <Link href={`/categories/${service.categorySlug}/${service.slug}`} className="group block overflow-hidden rounded-2xl border border-border bg-card shadow-card transition-all active:scale-[0.98] md:rounded-3xl md:hover:-translate-y-1 md:hover:shadow-elevated"><div className={`relative overflow-hidden bg-muted/30 ${size === "md" && !compact ? "aspect-[4/3]" : "aspect-square"}`}><Image src={service.images[0] ?? "/placeholder.svg"} alt={service.name} fill loading="lazy" sizes="(min-width: 768px) 25vw, 50vw" className="object-contain p-2 transition-transform duration-500 group-hover:scale-[1.02]" /><span className="absolute left-2 top-2 rounded-full bg-white/90 px-2 py-0.5 text-[9px] font-bold uppercase tracking-wide text-primary shadow-sm backdrop-blur">{service.conditionGrade?.replace("_", " ") ?? "Pre-owned"}</span></div><div className="p-3"><h3 className="line-clamp-2 min-h-9 font-bold leading-tight text-primary">{service.name}</h3><p className="mt-1 truncate text-xs text-muted-foreground">{service.brand ?? service.tagline}</p><div className="mt-2 flex items-center gap-1.5 text-xs"><span className="inline-flex items-center gap-0.5 rounded-full bg-[#12ad4b] px-1.5 py-0.5 font-bold text-white"><Star className="h-3 w-3 fill-current" />{service.rating.toFixed(1)}</span><span className="text-muted-foreground">{available > 0 ? `${available} in stock` : "Sold out"}</span></div><div className="mt-3 flex items-baseline gap-1.5 border-t border-border pt-3"><span className="text-base font-bold text-primary">₹{service.priceDiscounted.toLocaleString("en-IN")}</span>{service.priceOriginal > service.priceDiscounted && <span className="text-[11px] text-muted-foreground line-through">₹{service.priceOriginal.toLocaleString("en-IN")}</span>}</div>{!compact && <span className="mt-3 flex w-full items-center justify-center rounded-xl bg-primary px-3 py-2.5 text-[11px] font-bold uppercase tracking-wide text-primary-foreground">Buy now</span>}</div></Link>;
}
