import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { TopBar } from "@/components/TopBar";
import { BottomNav } from "@/components/BottomNav";
import { CONTACT, CONTACT_ADDRESS_FULL } from "@/lib/site";

export const metadata: Metadata = { title: "Terms & Conditions", description: "Terms governing purchases of pre-owned items on Hulumart.", alternates: { canonical: "/terms" } };
const updated = "August 23, 2026";
const sections = [
  ["1. Marketplace and acceptance", "Hulumart is an online marketplace for pre-owned, open-box, and refurbished items. By creating an account, placing an order, or using the website, you agree to these Terms. If you do not agree, do not use the service."],
  ["2. Product listings and condition", "Items are sold in the condition described in the listing. Product photographs, condition grade, age, usage notes, included and excluded accessories, warranty details, and delivery information form part of the listing. Images are illustrative of the listed item but screen settings can affect colour. Please review every listing carefully before ordering and contact us before purchase if anything is unclear."],
  ["3. Pre-owned items", "Pre-owned goods can show cosmetic wear and may not include original packaging, manuals, accessories, software, or manufacturer support unless expressly stated. Normal wear consistent with the published condition grade is not a defect. Compatibility, fit, installation requirements, consumables, and suitability for a particular purpose are the buyer’s responsibility unless expressly guaranteed in writing."],
  ["4. Availability and order acceptance", "Placing an order requests that we reserve an item; it is not an unconditional acceptance of the order. Stock can change before confirmation. We may decline, cancel, or limit an order for unavailability, pricing or listing errors, suspected fraud, safety concerns, or other legitimate operational reasons. If payment has been collected for an order we cancel, the applicable amount will be refunded."],
  ["5. Prices and payment", "Prices are shown in Indian Rupees and may change before an order is confirmed. Taxes, delivery charges, and any payment options are shown at checkout where applicable. You must provide accurate contact, delivery, and payment information. We may use third-party providers to process payments; we do not store full card or bank credentials."],
  ["6. Delivery, pickup and risk", "Delivery or pickup estimates are estimates, not guaranteed times. You must provide an accurate address and be available to receive the item or arrange authorised pickup. Risk passes to you when the item is delivered to the address or collected by you or your authorised representative. Please inspect the external package and item promptly, and report transit damage or a material mismatch with the listing with clear photos as soon as possible."],
  ["7. Cancellations, returns and refunds", "Cancellation, return, exchange, and refund eligibility depends on the listing, item condition, and applicable law. A return request may be refused where an item has been used, damaged, altered, is missing included parts, or does not match its returned condition. We may inspect a returned item before determining any refund. Nothing in these Terms limits non-excludable rights available under applicable law."],
  ["8. Warranties", "Only a warranty expressly shown on the product listing applies. Manufacturer warranties are subject to the manufacturer’s rules, remaining term, eligibility, transferability, and claim process. Unless stated in the listing or required by law, Hulumart gives no separate warranty and does not guarantee future performance, uninterrupted operation, or compatibility of a used item."],
  ["9. Buyer conduct", "You must not misuse the service, provide false details, attempt unauthorised payments, interfere with the site, or use content or listings for unlawful purposes. We may suspend or close accounts where we reasonably believe these Terms or the law have been breached."],
  ["10. Liability", "To the maximum extent permitted by law, Hulumart’s total liability relating to an item or order is limited to the amount paid to Hulumart for that item or order. We are not liable for indirect, incidental, special, consequential, business, data, or lost-profit losses. This does not exclude liability that cannot legally be excluded."],
  ["11. Intellectual property and changes", "The Hulumart name, website, content, photographs, and software are owned by or licensed to Hulumart and may not be copied or used commercially without permission. We may update these Terms; the date above shows the latest version. Continued use after an update means you accept the revised Terms."],
  ["12. Law, disputes and contact", `These Terms are governed by the laws of India, subject to mandatory consumer protections. Courts in Bengaluru, Karnataka have jurisdiction where legally permitted. Contact us at ${CONTACT.email}, ${CONTACT.phone}, or ${CONTACT_ADDRESS_FULL}.`],
] as const;

export default function TermsPage() { return <div className="min-h-dvh bg-background pb-24"><TopBar /><main className="mx-auto w-full max-w-3xl px-5 pb-16 pt-2 md:px-8"><Link href="/" className="inline-flex items-center gap-1 text-sm font-semibold text-muted-foreground"><ArrowLeft className="h-4 w-4" /> Back</Link><h1 className="mt-6 font-display text-4xl leading-tight md:text-5xl">Terms &amp; Conditions</h1><p className="mt-2 text-sm text-muted-foreground">Last updated: {updated}</p><div className="mt-8 space-y-8">{sections.map(([heading, body]) => <section key={heading}><h2 className="font-display text-xl md:text-2xl">{heading}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground md:text-base">{body}</p></section>)}</div></main><BottomNav /></div>; }
