"use client";

import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CircleHelp, HeartHandshake, Loader2, PackageCheck, Plus, Truck, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Kind = "included_set" | "faq_set" | "delivery_note" | "care_note";
type Faq = { question: string; answer: string };
const types: { value: Kind; label: string; title: string; icon: typeof PackageCheck }[] = [
  { value: "included_set", label: "What's included", title: "What's included", icon: PackageCheck },
  { value: "faq_set", label: "FAQs", title: "FAQs", icon: CircleHelp },
  { value: "delivery_note", label: "Delivery", title: "Delivery note", icon: Truck },
  { value: "care_note", label: "Care info", title: "Care info", icon: HeartHandshake },
];
const input = "mt-1 w-full rounded-xl border border-border bg-background px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-primary";
const queryKey = ["product-content-library"];
async function getItems() { const { data, error } = await createClient().from("product_content_library").select("*").order("name"); if (error) throw error; return data; }

export default function ProductContentLibraryPage() {
  const client = useQueryClient();
  const { data: all = [], isLoading } = useQuery({ queryKey, queryFn: getItems });
  const [active, setActive] = useState<Kind>("included_set"); const [open, setOpen] = useState(false);
  const selected = types.find((item) => item.value === active)!; const items = all.filter((item) => item.kind === active);
  return <section className="mx-auto max-w-6xl"><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-display text-2xl">Product content library</h2><p className="mt-1 text-sm text-muted-foreground">Reusable groups that can be assigned to product listings.</p></div><button onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground"><Plus className="h-4 w-4" />Create</button></div><div className="overflow-hidden rounded-3xl border border-border bg-card"><div className="flex flex-wrap gap-2 border-b border-border p-4">{types.map((item) => { const Icon = item.icon; return <button key={item.value} onClick={() => setActive(item.value)} className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold ${active === item.value ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground hover:bg-muted"}`}><Icon className="h-4 w-4" />{item.label}</button>; })}</div><div className="min-h-48 p-5">{isLoading ? <Loader2 className="mx-auto mt-10 h-5 w-5 animate-spin" /> : items.length === 0 ? <p className="py-12 text-center text-sm text-muted-foreground">No {selected.label.toLowerCase()} groups yet. Use Create to add one.</p> : <div className="grid gap-3 sm:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-2xl border border-border p-4"><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-muted-foreground">{active === "included_set" ? `${item.included.length} included item(s)` : active === "faq_set" ? `${Array.isArray(item.faqs) ? item.faqs.length : 0} question(s)` : item.body}</p></article>)}</div>}</div></div>{open && <CreateDialog kind={active} title={selected.title} onClose={() => setOpen(false)} onSaved={async () => { setOpen(false); await client.invalidateQueries({ queryKey }); }} />}</section>;
}

function CreateDialog({ kind, title, onClose, onSaved }: { kind: Kind; title: string; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(""); const [included, setIncluded] = useState([""]); const [notIncluded, setNotIncluded] = useState<string[]>([]); const [faqs, setFaqs] = useState<Faq[]>([{ question: "", answer: "" }]); const [body, setBody] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const clean = (items: string[]) => items.map((item) => item.trim()).filter(Boolean);
  async function save(event: React.FormEvent) { event.preventDefault(); if (!name.trim()) return setError("Group name is required."); setSaving(true); setError(""); const { error: saveError } = await createClient().from("product_content_library").insert({ kind, name: name.trim(), included: clean(included), not_included: clean(notIncluded), faqs: faqs.filter((item) => item.question.trim() && item.answer.trim()), body: body.trim() || null }); setSaving(false); if (saveError) return setError(saveError.message); onSaved(); }
  return <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/45 p-4"><form onSubmit={save} className="max-h-[90dvh] w-full max-w-3xl overflow-y-auto rounded-[2rem] bg-card shadow-2xl"><header className="flex items-start justify-between border-b border-border px-6 py-5"><div><h3 className="font-display text-3xl">Create {title}</h3><p className="mt-1 text-sm text-muted-foreground">Reusable across matching product fields.</p></div><button type="button" onClick={onClose} aria-label="Close" className="rounded-full border border-border p-2"><X className="h-4 w-4" /></button></header><div className="space-y-5 px-6 py-5"><label className="block text-sm font-semibold">Group name<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder={`e.g. Premium ${title}`} className={input} /></label>{kind === "included_set" && <><LineEditor title="Included" items={included} setItems={setIncluded} required /><LineEditor title="Not included (optional)" items={notIncluded} setItems={setNotIncluded} /></>}{kind === "faq_set" && <FaqEditor faqs={faqs} setFaqs={setFaqs} />}{(kind === "delivery_note" || kind === "care_note") && <label className="block text-sm font-semibold">{kind === "delivery_note" ? "Delivery details" : "Care details"}<textarea value={body} onChange={(event) => setBody(event.target.value)} rows={7} className={input} /></label>}{error && <p className="rounded-xl bg-destructive/10 p-3 text-sm font-semibold text-destructive">{error}</p>}</div><footer className="flex justify-end gap-3 border-t border-border px-6 py-5"><button type="button" onClick={onClose} className="rounded-full border border-border px-5 py-2.5 text-sm font-bold">Cancel</button><button disabled={saving} className="rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-50">{saving ? "Saving…" : "Save group"}</button></footer></form></div>;
}
function LineEditor({ title, items, setItems, required = false }: { title: string; items: string[]; setItems: React.Dispatch<React.SetStateAction<string[]>>; required?: boolean }) { return <div><p className="text-sm font-semibold">{title}</p><div className="mt-2 space-y-2">{items.map((item, index) => <div key={index} className="flex gap-2"><input required={required && index === 0} value={item} onChange={(event) => setItems((all) => all.map((value, i) => i === index ? event.target.value : value))} className={input} /><button type="button" onClick={() => setItems((all) => all.filter((_, i) => i !== index))} className="mt-1 rounded-full px-3 text-destructive" aria-label="Remove line">×</button></div>)}</div><button type="button" onClick={() => setItems((all) => [...all, ""])} className="mt-3 rounded-full border border-border px-4 py-2 text-sm font-semibold">+ Add line</button></div>; }
function FaqEditor({ faqs, setFaqs }: { faqs: Faq[]; setFaqs: React.Dispatch<React.SetStateAction<Faq[]>> }) { return <div className="space-y-3">{faqs.map((faq, index) => <div key={index} className="space-y-2 rounded-2xl border border-border p-4"><input value={faq.question} onChange={(event) => setFaqs((all) => all.map((item, i) => i === index ? { ...item, question: event.target.value } : item))} placeholder="Question" className={input} /><textarea value={faq.answer} onChange={(event) => setFaqs((all) => all.map((item, i) => i === index ? { ...item, answer: event.target.value } : item))} placeholder="Answer" rows={3} className={input} />{faqs.length > 1 && <button type="button" onClick={() => setFaqs((all) => all.filter((_, i) => i !== index))} className="text-xs font-bold text-destructive">Remove question</button>}</div>)}<button type="button" onClick={() => setFaqs((all) => [...all, { question: "", answer: "" }])} className="rounded-full border border-border px-4 py-2 text-sm font-semibold">+ Add question</button></div>; }
